{
    "name": "Monynha Theme",
    "summary": "Monynha Softwares brutalist-digital identity for Odoo Website",
    "version": "19.0.4.0.0",
    "category": "Theme/Creative",
    "sequence": 120,
    "author": "Monynha Softwares",
    "website": "https://monynha.com",
    "license": "LGPL-3",
    "depends": ["theme_common", "website"],
    "data": [
        "data/ir_asset.xml",
        "views/snippets.xml",
        "views/snippets_m2.xml",
        "views/snippets_m3.xml",
        "views/snippets_m4.xml",
        "data/page_templates_m4.xml",
        "data/pages.xml",
        "data/menu.xml",
    ],
    "images": ["static/description/theme_monynha.svg"],
    "images_preview_theme": {},
    "configurator_snippets": {
        "homepage": [
            "s_monynha_hero",
            "s_monynha_signal",
            "s_monynha_services",
            "s_monynha_selected_work",
            "s_monynha_principles",
            "s_monynha_labs_showcase",
            "s_monynha_manifesto",
            "s_monynha_cta",
        ],
    },
    "assets": {
        "web.assets_frontend": [
            "theme_monynha/static/src/scss/tokens.scss",
            "theme_monynha/static/src/scss/components.scss",
            "theme_monynha/static/src/scss/snippets.scss",
            "theme_monynha/static/src/scss/website.scss",
        ],
    },
    "installable": True,
    "application": False,
}
